/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class HelloWorld */

#ifndef _Included_HelloWorld
#define _Included_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorld
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWorld_print
  (JNIEnv *, jobject);

    
    int s1, s2;
    int s1s2;
    //s1=2;
    //s2=4;
    
   // double** range_map(double newmatrix2[5412][7216], double minimum, double maximum);
    double** range_map(double** newmatrix2, double minimum, double maximum);
    
    
    double* quickSort(double a[], long l, long r);//s1*s2
    
    int compare_doubles (const double *a, const double *b);
    
    long partition( double a[], long l, long r);//s1*s2
    
    //double* Percentile(double arr[5412][7216], double percentile[5]);
    
    double* Percentile(double** arr, double percentile[5]);
    
    
    
#ifdef __cplusplus
}
#endif
#endif
